name: common
description: Common action

outputs:
  rev-date:
    description: "Revision date"
    value: ${{ steps.common-vars.outputs.rev-date }}
  rev-unique:
    description: "Revision unique"
    value: ${{ steps.common-vars.outputs.rev-unique }}
  rev-name:
    description: "Revision name"
    value: ${{ steps.common-vars.outputs.rev-name }}
  branch-version:
    description: "Branch version"
    value: ${{ steps.common-vars.outputs.branch-version }}
  workflow-tmp-dir:
    description: "Workflow tmp dir"
    value: ${{ steps.tmp-dir.outputs.workflow-tmp-dir }}

runs:
  using: "composite"
  steps:

    - name: Cleanup workspace
      shell: bash
      run: |
        set -euo pipefail
        rm -rf $GITHUB_WORKSPACE/*

    - name: Generate and publish common vars
      id: common-vars
      shell: bash
      run: |
        set -euo pipefail

        REV_DATE=$(date +'%Y%m%d-%H%M%S')
        echo "rev-date=$REV_DATE" >> $GITHUB_OUTPUT
        echo "rev-date=$REV_DATE"

        RUN_NUMBER=${{ github.run_number }}
        RUN_ATTEMPT=${{ github.run_attempt }}

        REV_UNIQUE=$((RUN_NUMBER * 100 + RUN_ATTEMPT))
        echo "rev-unique=$REV_UNIQUE" >> $GITHUB_OUTPUT
        echo "rev-unique=$REV_UNIQUE"

        REV_NAME="v${RUN_NUMBER}-r${RUN_ATTEMPT}"
        echo "rev-name=$REV_NAME" >> $GITHUB_OUTPUT
        echo "rev-name=$REV_NAME"

        BRANCH_POSTFIX=$(echo "${{ github.ref }}" | sed -E 's|(.+)/v?(.+)|\2|')
        if [[ "$BRANCH_POSTFIX" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "branch-version=$BRANCH_POSTFIX" >> $GITHUB_OUTPUT
            echo "branch-version=$BRANCH_POSTFIX"
        else
            echo "___branch-version is not a semver___"
        fi

    - name: Clear and create temp dir
      id: tmp-dir
      shell: bash
      run: |
        set -euo pipefail

        WORKFLOW_TMP_DIR="./.tmp"
        WORKFLOW_TMP_DIR=$(cd $WORKFLOW_TMP_DIR && pwd)
        echo "WORKFLOW_TMP_DIR: $WORKFLOW_TMP_DIR"

        echo "clearing $WORKFLOW_TMP_DIR"
        rm -rf $WORKFLOW_TMP_DIR

        echo "creating $WORKFLOW_TMP_DIR"
        mkdir -p $WORKFLOW_TMP_DIR

        echo "WORKFLOW_TMP_DIR is ready!"
        echo "workflow-tmp-dir=$WORKFLOW_TMP_DIR" >> $GITHUB_OUTPUT
        echo "workflow-tmp-dir=$WORKFLOW_TMP_DIR"
